apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db-statefulset
  namespace: my-namespace
spec:
  serviceName: "my-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: my-db-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: my-db-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: my-db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
